version: '3.8'

services:
  web:
    build: ./web
    command: python manage.py run
    volumes:
      - ./web/:/usr/src/app/:z
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:14-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
