# syntax=docker/dockerfile:1
FROM node:18-bullseye-slim
ENV NODE_ENV=development

# Default location for subsequent commands
WORKDIR /app

# Install packages
COPY package.json ./
RUN yarn install --verbose

# Add code to image
COPY ./server.js ./server.js

# Start server
CMD node ./server.js
