services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8123:8000
    env_file:
      - ./.env.local
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - templateapp:/var/lib/postgresql/data/
    env_file:
      - ./.env.local.db

volumes:
  templateapp:
