services:
  nginx:
    build: nginx
    volumes:
      - static_files:/home/app/web/staticfiles
    ports:
      - 8123:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn templateproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_files:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.local
    environment:
      - DEBUG=0
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - templateapp:/var/lib/postgresql/data/
    env_file:
      - .env.local.db

volumes:
  templateapp:
  static_files:
