# Generated by Django 4.1.1 on 2022-10-03 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('content', models.TextField(blank=True, default='', max_length=1024)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'ToDo Item',
                'ordering': ['-updated_at', '-created_at', 'completed', 'title'],
                'get_latest_by': ['-updated_at', '-created_at', 'completed', 'title'],
            },
        ),
    ]
